[package]
name = "bpf-linker"
version = "0.9.6"
authors = ["Alessandro Decina <alessandro.d@gmail.com>"]
description = "BPF static linker"
license = "MIT OR Apache-2.0"
keywords = ["BPF", "eBPF", "linker", "llvm"]
categories = ["development-tools", "command-line-utilities", "no-std", "os::linux-apis"]
repository = "https://github.com/aya-rs/bpf-linker"
readme = "README.md"
edition = "2021"

[dependencies]
# cli deps
clap = { version = "4.0", features = ["derive"] }
simplelog = { version = "0.7.6" }

# lib deps
libc = "0.2"
thiserror = { version = "1.0" }
ar = { version = "0.8" }
log = { version = "0.4" }
llvm-sys = { version = "160" }
aya-rustc-llvm-proxy = { version = "0.5.0", optional = true }

[dev-dependencies]
compiletest_rs = { version = "0.5", path = "third-party/compiletest-rs" }
which = "4.2"

[[bin]]
name = "bpf-linker"

[features]
system-llvm = []
rust-llvm = [
    "aya-rustc-llvm-proxy",
    "llvm-sys/no-llvm-linking",
    "llvm-sys/disable-alltargets-init"
]
default = ["rust-llvm"]
